services:
  - type: web
    name: erp-system
    runtime: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npx prisma db push && node scripts/deploy-demo.js && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_1hwYMH4QaAmz@ep-soft-credit-anm9kca3.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: erp-system-production-secret-key-2026-change-in-production
      - key: NEXTAUTH_SECRET
        value: 91e69c722acb1ddf08a50b766a4cd0ff688a083e3d8c2ec671e87d83dc5f93f76acfdc316a31c87926b1d8c9f88571bd8bdfb466860c6e3f476b480b2cbef14e
      - key: NEXTAUTH_URL
        value: https://erp-system-btoq.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://erp-system-btoq.onrender.com/api

